#配置tomcat端口号
server:
  port: 8080

#项目名
spring:
  application:
    name: sb1

  #静态资源的配置
#  web:
#    resources:
#      static-locations:

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tests
    username: root
    password: root

# 配置mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志
    map-underscore-to-camel-case: true    # 驼峰命名

user:
  name: lixu
  age: 18